version: '3.9'

services:
  database:
    image: mysql
    container_name: Spring-Alura-JPA
    restart: always
    ports:
      - ?:?
    environment:
      MYSQL_ROOT_PASSWORD: ?
      MYSQL_DATABASE: Spring-Alura-JPA
      MYSQL_USER: ?
      MYSQL_PASSWORD: ?
    volumes:
      - pgdata:/data/mysql

volumes:
  pgdata:
    driver: local
