version: '3.9'

services:
  database:
    image: mysql
    container_name: Spring-Alura-JPA
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: Spring-Alura-JPA
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - pgdata:/data/mysql

volumes:
  pgdata:
    driver: local